source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import  path, include

from webapp.views import IntroViewList
from webapp.views.quiz_view import QuizCreateView

urlpatterns = [
    path('', IntroViewList.as_view(), name='intro'),
    path('quiz/create/', QuizCreateView.as_view(), name='quiz_create')
]

app_name = 'webapp'

source/webapp/models.py
from django.db import models


class Intro(models.Model):
    title = models.CharField(max_length=250, verbose_name='Intro title')
    author = models.ForeignKey('auth.User', related_name='author_intro', on_delete=models.SET_NULL,
                               null=True, blank=True, verbose_name='Quiz Author')
    author_link = models.CharField(max_length=150, null=True, blank=True, verbose_name='Author Link')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Intro description')
    image = models.ImageField(upload_to='intro_images', null=True, blank=True, verbose_name='Intro image')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Date Created')

    def __str__(self):
        return self.author.username

    class Meta:
        verbose_name = 'Intro'
        verbose_name_plural = 'Intro'


class Quiz(models.Model):
    author = models.ForeignKey('auth.User', related_name='question_author', on_delete=models.PROTECT, verbose_name='Author')
    question = models.CharField(max_length=250, verbose_name='Question')
    image = models.ImageField(upload_to='question_images', null=True, blank=True, verbose_name='Question photo')
    question_hint = models.TextField(max_length=2000, verbose_name='Question hint')

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Quiz'
        verbose_name_plural = 'Quizes'


class QuizOptions(models.Model):
    quiz = models.ForeignKey('webapp.Quiz', related_name='options', on_delete=models.CASCADE, verbose_name='Question')
    user_quiz_answer= models.TextField(max_length=200, verbose_name='Options')

    def __str__(self):
        return self.user_quiz_answer

    class Meta:
        verbose_name = 'Quiz Option'
        verbose_name_plural = 'Quiz Options'

source/webapp/forms.py
from django import forms

from webapp.models import Quiz


class QuizCreateForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['author','question', 'image', 'question_hint']

source/webapp/views/intro_view.py
from django.views.generic import ListView

from webapp.models import Intro, Quiz


class IntroViewList(ListView):
    model = Intro
    context_object_name = 'post_intro'
    template_name = 'webapp/intro/intro_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['quizes'] = Quiz.objects.all()
        return context

source/webapp/views/quiz_view.py
from django.urls import reverse
from django.views.generic import CreateView

from webapp.forms import QuizCreateForm
from webapp.models import Quiz


class QuizCreateView(CreateView):
    model = Quiz
    template_name = 'webapp/quiz/quiz_create.html'
    form_class = QuizCreateForm

    def form_valid(self, form):
        if str(self.request.user) != 'AnonymousUser':
            form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:intro')

source/webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    {% block title %}<title>Quiz</title>{% endblock %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'webapp:intro' %}">Home <span class="sr-only">(current)</span></a>
                  <a class="nav-item nav-link" href="#">Add Intro</a>
                  <a class="nav-item nav-link" href="{% url 'webapp:quiz_create' %}">Add Quiz</a>
                  {% block menu %} {% endblock %}
                  <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </div>
        </div>
    </nav>
  </head>
  <body>
  <div class="container">
      {% block content %} {% endblock %}
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  {% block js %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

source/webapp/templates/partial/form.html
{% load widget_tweaks %}
{% csrf_token %}
{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}
{% for field in form %}
    <div class="form-group">
        {% include 'partial/form_field.html' %}
    </div>
{% endfor %}

source/webapp/templates/partial/form_field.html
{% load widget_tweaks %}
<label for="{{ field.id_label }}" class="mr-3">{{ field.label }}</label>
{% if field|field_type == 'imagefiled' or field|field_type == 'filefield' or field|field_type == 'booleanfield' %}
    {{ field }}
{% else %}
    {{ field|add_class:"form-control" }}
{% endif %}
{% for error in field.errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

source/webapp/templates/webapp/intro/intro_list.html
{% extends 'base.html' %}
{% block content %}
    {% for test in post_intro %}
        <div class="card mb-3">
            {% if test.image %}
                <img src="{{ test.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ test.title }}</h5>
                <p class="card-text">{{ test.description }}</p>
                <p class="card-text"><small class="text-muted"> By {{ test.author }} at {{ test.created_at }}</small></p>
            </div>
        </div>
    {% endfor %}
    {% for quiz in quizes %}
        <div class="row row-cols-2 row-cols-md-1">
            <div class="col mb-4">
                <div class="card">
                    <img src="{{ quiz.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5>Question - {{ quiz.pk }}</h5>
                        <h5 class="card-title">{{ quiz.question }}</h5>
                        <p class="card-text">{{ quiz.question_hint }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

source/webapp/templates/webapp/quiz/quiz_create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Add quiz</h1>
        <form action="{% url 'webapp:quiz_create'  %}" method="POST" enctype="multipart/form-data">
            {% include 'partial/form.html' %}
            <input type="submit" value="Add quiz" class="btn btn-primary">
            <a class="btn btn-secondary" href="{% url 'webapp:intro' %}">Cancel</a>
        </form>
    </div>
{% endblock %}